### ISSUE TITLE
testing iso's 1 & 2

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/lunar-iso#20] opened 2015-06-15 18:40 UTC
![img_0257](https://cloud.githubusercontent.com/assets/5716768/8167327/c349c0a4-139d-11e5-8b7b-2a5291f3a3b4.JPG)
See the picture above! I have this on both iso's, testing1 & testing2. (1.7.1).
My pc is a laptop:
Lenovo X230
i5 3320
Intel HD graphics i915

Perhaps a known issue?
Regards,
Marco

**Comment by mwgrient** [comment] 2015-06-15 18:43
Goodness! What I was trying to say is that the picture shows that my laptop hangs at that point.

**Comment by Ratler** [comment] 2015-06-15 19:26
@mwgrient you could try passing on a few options to the kernel when booting. For example type: install nomodeset acpi=off noapic nolapic

Try one of them at a time so you can figure out which one that might be causing you issues.

**Comment by mwgrient** [comment] 2015-06-15 20:02
![img_0259](https://cloud.githubusercontent.com/assets/5716768/8169411/ae53c5e4-13a9-11e5-842d-797cca67bc1f.JPG)
Another picture! The kernel panic as shown is visible with the options: one after one I have tried them, and all together. All the same result.

**Comment by sofar** [comment] 2015-06-16 04:22
try adding vga=6 - it'll capture more output and may show you what the actual rootfs should be (which is likely to be the root cause here).

**Comment by mwgrient** [comment] 2015-06-16 05:10
![unnamed](https://cloud.githubusercontent.com/assets/5716768/8176106/10ab6e26-13f6-11e5-88a9-a487bcfc7959.jpg)
This is a picture with vga=6. Last year I had a similar issue with Dracut at boot with the testing iso. Good this be the case again?

**Comment by sofar** [comment] 2015-06-16 05:48
It's just not finding the root filesystem, How are you booting the ISO image? Or is this after installation?

**Comment by mwgrient** [comment] 2015-06-16 06:07
Ok.
- booting from a usb stick, made with "dd if=iso of=usb bs=1M"
- I am running 1.7.0 without any problems.
- So it is not after a installation. I can not install 1.7.1 testing 1 or 2 from usb, thats all. 
:-)
cheers.

**Comment by Ratler** [comment] 2015-07-05 21:54
I can confirm that I was unable to boot the latest testing ISO using an usb-stick. I'm fairly certain it's related to an old version of dracut. I'm preparing a testing3 ISO shortly.

**Comment by mwgrient** [comment] 2015-07-12 07:53
I am booting the newly iso testing3 from usb-stick! :-) And now I can install system 1.7.1.

**Comment by Ratler** [comment] 2016-04-02 16:01
Resolved, closing.

**Closed by Ratler** 2016-04-02 16:01 UTC
